services:
    client:
        build: ./client-service
        restart: unless-stopped
        ports:
            - "8081:8081"
        depends_on:
            - gateway

    gateway:
        build: ./gateway-service
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            - patient
            - note
            - risk-report

    patient:
        build: ./patient-service
        restart: unless-stopped
        ports:
            - "8082:8082"
        depends_on:
            - patient-db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-db:5432/medilabo?currentSchema=dev
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres

    patient-db:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_DB: medilabo
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    note:
        build: ./note-service
        ports:
            - "8083:8083"
        depends_on:
            - note-db
        environment:
            - SPRING_DATA_MONGODB_HOST=note-db
            - SPRING_DATA_MONGODB_PORT=27017
            - SPRING_DATA_MONGODB_DATABASE=medilabo

    note-db:
        image: mongo:7
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    risk-report:
        build: ./risk-report-service
        restart: unless-stopped
        ports:
            - "8084:8084"
        depends_on:
            - patient
            - note

volumes:
    postgres_data:
    mongo_data: