services:
    client:
        build:
            context: ./client-service
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8081:8081"
        depends_on:
            - gateway

    gateway:
        build:
            context: ./gateway-service
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            - patient
            - note
            - risk-report

    patient:
        build:
            context: ./patient-service
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8082:8082"
        depends_on:
            - patient-db
        env_file: .env
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-db:5432/${POSTGRES_DB}
            - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
            - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

    patient-db:
        image: postgres:16
        restart: unless-stopped
        env_file: .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    note:
        build:
            context: ./note-service
            dockerfile: Dockerfile
        ports:
            - "8083:8083"
        depends_on:
            - note-db
        environment:
            - SPRING_DATA_MONGODB_HOST=note-db
            - SPRING_DATA_MONGODB_PORT=27017
            - SPRING_DATA_MONGODB_DATABASE=medilabo

    note-db:
        image: mongo:7
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        environment:
            MONGO_INITDB_DATABASE: medilabo

    risk-report:
        build:
            context: ./risk-report-service
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8084:8084"
        depends_on:
            - patient
            - note

volumes:
    postgres_data:
    mongo_data: